Repository codeblooded/grpc, pull requests merged in 2020-04, with the labels that each got.

#70 Storage component for benchmarking service.
  testctrl/svc/store/storage_server.go
  testctrl/svc/store/storage_server_test.go
Labels: enhancement

#71 Add executable and coverage files to .gitignore
  testctrl/.gitignore
Labels: cleanup

#65 Clean up Dockerfiles for languages and driver
  testctrl/kubernetes/images/cxx/Dockerfile
  testctrl/kubernetes/images/cxx/deployments.yaml
  testctrl/kubernetes/images/driver/Dockerfile
  testctrl/kubernetes/images/java/Dockerfile
  testctrl/kubernetes/images/java/deployments.yaml
Labels: P1, enhancement

#72 Fix NewEvent constructor to return a pointer.
  testctrl/svc/store/storage_server_test.go
  testctrl/svc/types/event.go
Labels: P2, cleanup

#74 Add driver logs to events and rename event message
  testctrl/proto/scheduling/v1/scheduling_service.pb.go
  testctrl/proto/scheduling/v1/scheduling_service.proto
  testctrl/svc/store/storage_server_test.go
  testctrl/svc/types/event.go
Labels: P0, enhancement

#76 Set WORKER_KIND env variable for servers & clients
  testctrl/svc/orch/spec_builder.go
  testctrl/svc/orch/spec_builder_test.go
Labels: P2, bug

#75 Refactor orch package
  testctrl/cmd/orchtest/main.go
  testctrl/cmd/svc/main.go
  testctrl/go.sum
  testctrl/svc/orch/controller.go
  testctrl/svc/orch/controller_test.go
  testctrl/svc/orch/doc.go
  testctrl/svc/orch/executor.go
  testctrl/svc/orch/executor_test.go
  testctrl/svc/orch/health.go
  testctrl/svc/orch/internal_test.go
  testctrl/svc/orch/monitor.go
  testctrl/svc/orch/monitor_test.go
  testctrl/svc/orch/object.go
  testctrl/svc/orch/object_test.go
  testctrl/svc/orch/pod_interfaces.go
  testctrl/svc/orch/pool_test.go
  testctrl/svc/orch/queue.go
  testctrl/svc/orch/queue_test.go
  testctrl/svc/orch/reservation.go
  testctrl/svc/orch/reservation_test.go
  testctrl/svc/orch/spec_builder.go
  testctrl/svc/orch/spec_builder_test.go
  testctrl/svc/orch/testing.go
  testctrl/svc/orch/watcher.go
  testctrl/svc/orch/watcher_test.go
Labels: P2, cleanup
