Repository codeblooded/grpc, pull requests merged in 2020-05, with the labels that each got.

#82 Save orchestration events in the store
  testctrl/cmd/orchtest/main.go
  testctrl/svc/orch/controller.go
  testctrl/svc/orch/controller_test.go
  testctrl/svc/orch/executor.go
  testctrl/svc/orch/executor_test.go
Labels: P2, enhancement

#79 Add elementary validator package to combat bad sessions
  testctrl/svc/validator/doc.go
  testctrl/svc/validator/validator.go
  testctrl/svc/validator/validator_test.go
Labels: P2, enhancement

#78 Add operations service and scheduling service.
  testctrl/auth/auth.go
  testctrl/cmd/svc/main.go
  testctrl/svc/operations_server.go
  testctrl/svc/operations_server_test.go
  testctrl/svc/orch/spec_builder.go
  testctrl/svc/scheduling_server.go
  testctrl/svc/scheduling_server_test.go
  testctrl/svc/store/storage_server.go
  testctrl/svc/store/storage_server_test.go
  testctrl/svc/types/component.go
  testctrl/svc/types/session.go
  testctrl/svc/types/session_test.go
Labels: P1, enhancement

#89 Pass store to controller
  testctrl/cmd/svc/main.go
Labels: P1, feature

#90 Set pool using test session request proto
  testctrl/proto/scheduling/v1/scheduling_service.pb.go
  testctrl/proto/scheduling/v1/scheduling_service.proto
  testctrl/svc/scheduling_server.go
Labels: P1, bug

#91 Marshal internal event description into protobuf
  testctrl/svc/operations_server.go
Labels: P2, bug

#92 Fix blocking issue with multiple sessions
  testctrl/go.sum
  testctrl/svc/orch/controller.go
  testctrl/svc/orch/watcher.go
Labels: P0, bug

#95 Add low-fidelity CLI to schedule tests
  testctrl/cmd/testctl/main.go
  testctrl/go.sum
Labels: P1, cli

#100 Add options structs and timeouts to orch package
  testctrl/cmd/orchtest/main.go
  testctrl/cmd/svc/main.go
  testctrl/svc/orch/controller.go
  testctrl/svc/orch/controller_test.go
  testctrl/svc/orch/executor.go
  testctrl/svc/orch/executor_test.go
  testctrl/svc/orch/internal_test.go
  testctrl/svc/orch/watcher.go
  testctrl/svc/orch/watcher_test.go
Labels: P2, feature, security
